export const MESSAGE_TYPES = {
    GET_OPTIONS: 'GET_OPTIONS',
    SET_OPTIONS: 'SET_OPTIONS',
    GET_SESSIONS: 'GET_SESSIONS',
    RESTORE_SESSION: 'RESTORE_SESSION',
    SET_ICON_THEME: 'SET_ICON_THEME',
    SET_COLOR_SCHEME: 'SET_COLOR_SCHEME',
}